"""
Three-layer Cascading Entropy-Gated ML-KEM (CEG-KEM).

Architecture:
  Layer 1 — Entropy gate:   position entropy must be in acceptance band
  Layer 2 — Velocity gate:  no teleportation, session nonce not replayed
  Layer 3 — Quorum gate:    K-of-N recent chunks attest valid position + role check

Each layer runs an independent ML-KEM encapsulation.  The final decrypt
key is derived via HKDF from all three shared secrets concatenated.
Failure at ANY layer collapses the entire cascade — no partial key material
is ever returned.

ML-KEM status:
  The encapsulation is currently simulated with HKDF-SHA256 key derivation
  over random keying material.  The cascade architecture is structurally
  identical to real ML-KEM — swapping in ``liboqs`` or ``pqcrypto`` is a
  drop-in replacement at the ``_encapsulate`` / ``_decapsulate`` boundary.
  We do NOT call this "post-quantum secure" until that swap is done.
"""

from __future__ import annotations

import hashlib
import hmac
import os
import time
from dataclasses import dataclass, field
from enum import Enum
from collections import OrderedDict
from typing import Any, Dict, List, Optional, Set, Tuple

from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives import hashes

from backend.security.entropy import (
    AnomalyType,
    EntropyAnomalyDetector,
    EntropyResult,
    EntropyThresholds,
)
from backend.security.chunks import ChunkAttestor, PositionChunk, QuorumValidator
from backend.security.siem import EventType, SIEMLogger, Severity
from backend.security.uwb_proxy import UWBProxyClient


class CascadeFailureReason(str, Enum):
    """Why the cascade collapsed."""

    ENTROPY_ANOMALY = "entropy_anomaly"
    VELOCITY_EXCEEDED = "velocity_exceeded"
    REPLAY_DETECTED = "replay_detected"
    SESSION_NONCE_REUSED = "session_nonce_reused"
    QUORUM_FAILED = "quorum_failed"
    CHUNK_TAMPERED = "chunk_tampered"
    ROLE_DENIED = "role_denied"
    INSUFFICIENT_SAMPLES = "insufficient_samples"
    OUTSIDE_PERIMETER = "outside_perimeter"


@dataclass(frozen=True)
class CascadeResult:
    """Immutable result of a CEG-KEM cascade attempt."""

    success: bool
    decrypt_key: Optional[bytes]
    failure_reason: Optional[CascadeFailureReason]
    entropy_result: Optional[EntropyResult]
    quorum_details: Optional[Dict[str, object]]
    layer_reached: int  # 0 = pre-check, 1/2/3 = failed at or passed that layer
    cascade_id: str


# ---------------------------------------------------------------------------
# Simulated ML-KEM keypair
# ---------------------------------------------------------------------------

@dataclass
class SimulatedMLKEMKeypair:
    """
    Placeholder for a real ML-KEM-768 keypair.

    In production this would be generated by ``liboqs.KeyEncapsulation('ML-KEM-768')``.
    The simulation uses random bytes of the correct length to maintain
    structural compatibility.
    """

    public_key: bytes
    secret_key: bytes

    @classmethod
    def generate(cls) -> "SimulatedMLKEMKeypair":
        return cls(
            public_key=os.urandom(1184),  # ML-KEM-768 pk size
            secret_key=os.urandom(2400),  # ML-KEM-768 sk size
        )


def _simulated_encapsulate(
    public_key: bytes,
) -> Tuple[bytes, bytes]:
    """
    Simulate ML-KEM encapsulation.

    Returns (ciphertext, shared_secret).  In production, replace with:
        kem = liboqs.KeyEncapsulation('ML-KEM-768')
        ct, ss = kem.encap_secret(public_key)
    """
    shared_secret = os.urandom(32)
    # Simulate ciphertext as HMAC of pk + ss (deterministic for testing)
    ciphertext = hmac.new(public_key[:32], shared_secret, hashlib.sha256).digest()
    return (ciphertext, shared_secret)


def _simulated_decapsulate(
    secret_key: bytes,
    ciphertext: bytes,
) -> bytes:
    """
    Simulate ML-KEM decapsulation.

    In production, replace with:
        ss = kem.decap_secret(ciphertext)
    """
    return hmac.new(secret_key[:32], ciphertext, hashlib.sha256).digest()


# ---------------------------------------------------------------------------
# Spatial boundary and nonce management
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SpatialBoundary:
    """
    Server-side secure-zone perimeter definition.

    Coordinates use the same normalised 0-100 grid as position samples.
    This definition is kept STRICTLY server-side — exposing it to clients
    allows an attacker to craft coordinates that sit inside the acceptance
    band without physical presence.
    """

    x: float
    y: float
    width: float
    height: float

    def contains(self, px: float, py: float) -> bool:
        return (
            self.x <= px <= self.x + self.width
            and self.y <= py <= self.y + self.height
        )

    def contains_all(self, positions: List[Tuple[float, float]]) -> bool:
        """Return True only if every position sample falls within the boundary."""
        return all(self.contains(px, py) for px, py in positions)


class _NonceStore:
    """
    TTL-keyed, FIFO-evicting nonce rejection store.

    Fixes two bugs in the original ``set``-based store:
      1. ``set.pop()`` removes an *arbitrary* element — recently-used nonces
         could be silently evicted and then replayed.
      2. In-process state evaporates on restart; the TTL window makes a
         single-process deployment safe within the configured window.

    For multi-replica deployments replace this with a Redis TTL-keyed store.
    """

    def __init__(
        self,
        ttl_seconds: float = 60.0,
        max_size: int = 10_000,
    ) -> None:
        self._store: OrderedDict[str, float] = OrderedDict()
        self._ttl = ttl_seconds
        self._max_size = max_size

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def is_seen(self, nonce: str) -> bool:
        """Return True if the nonce is within the active replay-rejection window."""
        self._evict_expired()
        return nonce in self._store

    def add(self, nonce: str) -> None:
        """Record a nonce as consumed."""
        self._evict_expired()
        if nonce in self._store:
            return  # already recorded, idempotent
        if len(self._store) >= self._max_size:
            self._store.popitem(last=False)  # evict oldest by insertion order
        self._store[nonce] = time.time()

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _evict_expired(self) -> None:
        """Remove nonces older than the TTL window from the front of the store."""
        cutoff = time.time() - self._ttl
        while self._store:
            _, ts = next(iter(self._store.items()))
            if ts < cutoff:
                self._store.popitem(last=False)
            else:
                break


# ---------------------------------------------------------------------------
# Cascade engine
# ---------------------------------------------------------------------------


class CascadeMLKEM:
    """
    Three-layer cascading key encapsulation gated by entropy, velocity,
    session nonce, chunk quorum, and role validation.
    """

    def __init__(
        self,
        siem: Optional[SIEMLogger] = None,
        entropy_thresholds: Optional[EntropyThresholds] = None,
        chunk_attestor: Optional[ChunkAttestor] = None,
        quorum_validator: Optional[QuorumValidator] = None,
        allowed_roles: Optional[Set[str]] = None,
        min_samples: int = 6,
        boundary: Optional[SpatialBoundary] = None,
    ) -> None:
        self._siem = siem or SIEMLogger()
        self._detector = EntropyAnomalyDetector(entropy_thresholds)
        self._uwb_proxy = UWBProxyClient()
        self._attestor = chunk_attestor or ChunkAttestor()
        self._quorum = quorum_validator or QuorumValidator()
        self._allowed_roles = allowed_roles or {"operator", "admin"}
        self._min_samples = min_samples
        self._boundary = boundary

        # TTL-keyed nonce store — prevents replay within the active window.
        # For multi-replica deployments replace with a Redis-backed store.
        self._nonce_store = _NonceStore()

        # Generate three independent keypairs for the cascade layers
        self._keypairs = [SimulatedMLKEMKeypair.generate() for _ in range(3)]

    def execute(
        self,
        positions: List[Tuple[float, float]],
        timestamps: List[float],
        session_nonce: str,
        user_role: str,
        chunks: Optional[List[PositionChunk]] = None,
        source_ip: Optional[str] = None,
    ) -> CascadeResult:
        """
        Run the full three-layer CEG-KEM cascade.

        Returns a ``CascadeResult`` with the decrypt key on success,
        or a failure reason and the layer at which the cascade collapsed.
        """
        cascade_id = hashlib.sha256(
            f"{session_nonce}:{time.time()}".encode()
        ).hexdigest()[:16]

        shared_secrets: List[bytes] = []

        # ------------------------------------------------------------------
        # Pre-check: sufficient sample count
        # ------------------------------------------------------------------
        if len(positions) < self._min_samples:
            self._siem.emit(
                EventType.CASCADE_FAILURE,
                f"Cascade {cascade_id}: insufficient samples ({len(positions)})",
                {"cascade_id": cascade_id, "sample_count": len(positions)},
                source_ip=source_ip,
            )
            return CascadeResult(
                success=False,
                decrypt_key=None,
                failure_reason=CascadeFailureReason.INSUFFICIENT_SAMPLES,
                entropy_result=None,
                quorum_details=None,
                layer_reached=0,
                cascade_id=cascade_id,
            )

        # ------------------------------------------------------------------
        # Layer 1 — Entropy gate
        # ------------------------------------------------------------------
        entropy_result = self._uwb_proxy.verify_position(positions, timestamps)

        if entropy_result.anomaly != AnomalyType.GENUINE:
            event_type = (
                EventType.REPLAY_DETECTED
                if entropy_result.anomaly == AnomalyType.REPLAY
                else EventType.ENTROPY_ANOMALY
            )
            self._siem.emit(
                event_type,
                f"Cascade {cascade_id} collapsed at Layer 1: {entropy_result.anomaly.value}",
                {
                    "cascade_id": cascade_id,
                    "anomaly": entropy_result.anomaly.value,
                    "entropy_score": entropy_result.score,
                    "fingerprint": entropy_result.fingerprint,
                },
                source_ip=source_ip,
            )
            failure = (
                CascadeFailureReason.REPLAY_DETECTED
                if entropy_result.anomaly == AnomalyType.REPLAY
                else CascadeFailureReason.ENTROPY_ANOMALY
            )
            return CascadeResult(
                success=False,
                decrypt_key=None,
                failure_reason=failure,
                entropy_result=entropy_result,
                quorum_details=None,
                layer_reached=1,
                cascade_id=cascade_id,
            )

        # Layer 1 passed — encapsulate
        ct1, ss1 = _simulated_encapsulate(self._keypairs[0].public_key)
        shared_secrets.append(ss1)

        # ------------------------------------------------------------------
        # Layer 1.5 — Server-side spatial boundary gate
        # The perimeter is defined only in server config — never sent to
        # clients, preventing coordinate-crafting attacks.
        # ------------------------------------------------------------------
        if self._boundary is not None and not self._boundary.contains_all(positions):
            self._siem.emit(
                EventType.POSITION_REJECTED,
                f"Cascade {cascade_id} collapsed: positions outside server perimeter",
                {"cascade_id": cascade_id},
                source_ip=source_ip,
            )
            return CascadeResult(
                success=False,
                decrypt_key=None,
                failure_reason=CascadeFailureReason.OUTSIDE_PERIMETER,
                entropy_result=entropy_result,
                quorum_details=None,
                layer_reached=1,
                cascade_id=cascade_id,
            )

        # ------------------------------------------------------------------
        # Layer 2 — Velocity + session nonce gate
        # ------------------------------------------------------------------
        if entropy_result.velocity_max > (
            self._detector._thresholds.velocity_max
        ):
            self._siem.emit(
                EventType.VELOCITY_VIOLATION,
                f"Cascade {cascade_id} collapsed at Layer 2: velocity {entropy_result.velocity_max:.1f}",
                {
                    "cascade_id": cascade_id,
                    "velocity_max": entropy_result.velocity_max,
                },
                source_ip=source_ip,
            )
            return CascadeResult(
                success=False,
                decrypt_key=None,
                failure_reason=CascadeFailureReason.VELOCITY_EXCEEDED,
                entropy_result=entropy_result,
                quorum_details=None,
                layer_reached=2,
                cascade_id=cascade_id,
            )

        if self._nonce_store.is_seen(session_nonce):
            self._siem.emit(
                EventType.REPLAY_DETECTED,
                f"Cascade {cascade_id} collapsed at Layer 2: nonce reuse",
                {"cascade_id": cascade_id, "nonce": session_nonce},
                severity=Severity.CRITICAL,
                source_ip=source_ip,
            )
            return CascadeResult(
                success=False,
                decrypt_key=None,
                failure_reason=CascadeFailureReason.SESSION_NONCE_REUSED,
                entropy_result=entropy_result,
                quorum_details=None,
                layer_reached=2,
                cascade_id=cascade_id,
            )

        # Record nonce in the TTL-keyed FIFO store (evicts oldest by insertion order)
        self._nonce_store.add(session_nonce)

        # Layer 2 passed — encapsulate (requires ss1 for chaining)
        chain_input = ss1 + session_nonce.encode()
        ct2, ss2 = _simulated_encapsulate(
            self._keypairs[1].public_key
        )
        shared_secrets.append(ss2)

        # ------------------------------------------------------------------
        # Layer 3 — Quorum + role gate
        # ------------------------------------------------------------------
        if user_role not in self._allowed_roles:
            self._siem.emit(
                EventType.PRIVILEGE_DENIED,
                f"Cascade {cascade_id} collapsed at Layer 3: role '{user_role}' denied",
                {"cascade_id": cascade_id, "role": user_role},
                source_ip=source_ip,
            )
            return CascadeResult(
                success=False,
                decrypt_key=None,
                failure_reason=CascadeFailureReason.ROLE_DENIED,
                entropy_result=entropy_result,
                quorum_details=None,
                layer_reached=3,
                cascade_id=cascade_id,
            )

        quorum_details: Optional[Dict[str, object]] = None
        if chunks is not None:
            passed, quorum_details = self._quorum.validate(
                chunks, self._attestor
            )
            if not passed:
                self._siem.emit(
                    EventType.QUORUM_FAILURE,
                    f"Cascade {cascade_id} collapsed at Layer 3: quorum not met",
                    {
                        "cascade_id": cascade_id,
                        "quorum": quorum_details,
                    },
                    source_ip=source_ip,
                )
                return CascadeResult(
                    success=False,
                    decrypt_key=None,
                    failure_reason=CascadeFailureReason.QUORUM_FAILED,
                    entropy_result=entropy_result,
                    quorum_details=quorum_details,
                    layer_reached=3,
                    cascade_id=cascade_id,
                )

        # Layer 3 passed — encapsulate
        ct3, ss3 = _simulated_encapsulate(self._keypairs[2].public_key)
        shared_secrets.append(ss3)

        # ------------------------------------------------------------------
        # Derive final decrypt key via HKDF
        # ------------------------------------------------------------------
        combined = b"".join(shared_secrets)
        hkdf = HKDF(
            algorithm=hashes.SHA256(),
            length=32,
            salt=session_nonce.encode(),
            info=b"artemis-ceg-kem-v1",
        )
        decrypt_key = hkdf.derive(combined)

        self._siem.emit(
            EventType.DECRYPT_SUCCESS,
            f"Cascade {cascade_id} completed — decrypt key derived",
            {
                "cascade_id": cascade_id,
                "entropy_score": entropy_result.score,
                "role": user_role,
            },
            severity=Severity.INFO,
            source_ip=source_ip,
        )

        return CascadeResult(
            success=True,
            decrypt_key=decrypt_key,
            failure_reason=None,
            entropy_result=entropy_result,
            quorum_details=quorum_details,
            layer_reached=3,
            cascade_id=cascade_id,
        )
